name: Build and Push majicmix-realistic-v6

on:
  push:
    branches:
      - majicmix-realistic-v6

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      REPO_NAME: ${{ secrets.DOCKERHUB_REPO }}
      TAG: majicmix-realistic-v6
    steps:
      - uses: AutoModality/action-clean@v1
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Download Script
        run: ./images/${{ env.TAG }}/download.sh
        shell: bash

      - name: Build and Push
        run: ./build.sh ${{ env.REPO_NAME }} ${{ env.TAG }}
        shell: bash